services:
  huckleberry:
    build: .
    image: erikperkins/huckleberry:latest
    networks:
      - tombstone
    expose:
      - 8000
    ports:
      - 8001:8001
    volumes:
      - daisy:/app/data
      - /tmp:/tmp
      - ./:/app
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 1

  kate:
    build: ./services/nginx
    image: erikperkins/kate:latest
    networks:
      - tombstone
    ports:
      - 80:80
    volumes:
      - /tmp:/tmp
    depends_on:
      - huckleberry

volumes:
  daisy:

networks:
  tombstone:
