services:
  huckleberry:
    image: dockholliday:latest
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - kate
    volumes:
      - daisy:/app/data
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 0

volumes:
  daisy:

networks:
  kate:
